name: Release

on:
  push:
    tags: ["**/v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine module
        id: module
        env:
          TAG: ${{ github.ref_name }}
        run: echo "name=${TAG%%/*}" >> $GITHUB_OUTPUT

      - name: Publish module
        uses: dagger/dagger-for-github@847ae4458ef34fe9b5f566655957bde6d4891112 # v7.0.3
        with:
          module: ${{ steps.module.outputs.name }}
          verb: publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.15.1"
