name: Release

on:
  push:
    tags: ["**/v[0-9]+.[0-9]+.[0-9]+"]

env:
  DAGGER_VERSION: 0.19.9

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine module
        id: module
        env:
          TAG: ${{ github.ref_name }}
        run: echo "name=${TAG%%/*}" >> $GITHUB_OUTPUT

      - name: Publish module
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          module: ${{ steps.module.outputs.name }}
          verb: publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}
